### Create a new user
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "email": "testinguser@test.com",
    "password": "12345"

}

### Sign in user
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "email": "testinguser@test.com",
    "password": "12345"

}

### Sign out user
POST http://localhost:3001/auth/signout

### who is user
GET http://localhost:3001/auth/whoami


### Get one user
GET http://localhost:3001/auth/1

### Get user with a particular email
GET http://localhost:3001/auth?email=new@email.com

### Delete user with given id
DELETE http://localhost:3001/auth/

### Update a user
PATCH  http://localhost:3001/auth/2
Content-Type: application/json

{
    "password": "newnewpassword"
}
